_search_search:
    pattern: /search
    defaults: { _controller: MajesSearchBundle:Search:search }

_search_filtered_search:
    pattern: /search/filtered
    defaults: { _controller: MajesSearchBundle:Search:filteredSearch }