services:
    demo.tokens.action_listener:
        class: Majes\SearchBundle\EventListener\ControllerListener
        arguments: ["@majes.notification", "@fos_elastica.index.majesteel_back"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

#    majes_search.example:
#        class: %majes_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]