parameters:
#    majes_search.example.class: Majes\SearchBundle\Example

services:
#    majes_search.example:
#        class: %majes_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
