parameters:
    fos_elastica.client.class: Majes\SearchBundle\Elastica\ElasticaClient

services:
    demo.tokens.action_listener:
        class: Majes\SearchBundle\EventListener\ControllerListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

#    majes_search.example:
#        class: %majes_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]